Demo that rust_args doesn't work with dcbaker's branch
DEPRECATION: rust_args in the [properties] section of the machine file is deprecated, use the [built-in options] section.
The Meson build system
Version: 0.55.999
Source dir: /home/anholt/src/temp/rusttest
Build dir: /home/anholt/src/temp/rusttest/build-i386
Build type: cross build
Project name: rusttest
Project version: 1.0
C compiler for the host machine: /usr/lib/ccache/i686-linux-gnu-gcc (gcc 10.2.0 "i686-linux-gnu-gcc (Debian 10.2.0-9) 10.2.0")
C linker for the host machine: /usr/lib/ccache/i686-linux-gnu-gcc ld.bfd 2.35.1
C compiler for the build machine: ccache cc (gcc 10.2.0 "cc (Debian 10.2.0-9) 10.2.0")
C linker for the build machine: cc ld.bfd 2.35.1
Build machine cpu family: x86_64
Build machine cpu: x86_64
Host machine cpu family: x86_64
Host machine cpu: x86_64
Target machine cpu family: x86
Target machine cpu: i386
Rust compiler for the build machine: rustc -C linker=cc (rustc 1.47.0)
Rust linker for the build machine: rustc -C linker=cc ld.bfd 2.35.1

meson.build:11:0: ERROR: Rust compiler rustc -C linker=/usr/lib/ccache/i686-linux-gnu-gcc can not compile programs.

error: linking with `/usr/lib/ccache/i686-linux-gnu-gcc` failed: exit code: 1
  |
  = note: "/usr/lib/ccache/i686-linux-gnu-gcc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-Wl,--eh-frame-hdr" "-L" "/home/anholt/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/home/anholt/src/temp/rusttest/build-i386/meson-private/rusttest.sanity.7rcbfp3g-cgu.0.rcgu.o" "/home/anholt/src/temp/rusttest/build-i386/meson-private/rusttest.sanity.7rcbfp3g-cgu.1.rcgu.o" "/home/anholt/src/temp/rusttest/build-i386/meson-private/rusttest.sanity.7rcbfp3g-cgu.2.rcgu.o" "/home/anholt/src/temp/rusttest/build-i386/meson-private/rusttest.sanity.7rcbfp3g-cgu.3.rcgu.o" "/home/anholt/src/temp/rusttest/build-i386/meson-private/rusttest.sanity.7rcbfp3g-cgu.4.rcgu.o" "/home/anholt/src/temp/rusttest/build-i386/meson-private/rusttest.sanity.7rcbfp3g-cgu.5.rcgu.o" "/home/anholt/src/temp/rusttest/build-i386/meson-private/rusttest.sanity.7rcbfp3g-cgu.6.rcgu.o" "-o" "/home/anholt/src/temp/rusttest/build-i386/meson-private/rusttest" "/home/anholt/src/temp/rusttest/build-i386/meson-private/rusttest.y3ku8mxgq5v8qc0.rcgu.o" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro" "-Wl,-znow" "-nodefaultlibs" "-L" "/home/anholt/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,--start-group" "-Wl,-Bstatic" "/home/anholt/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-f14aca24435a5414.rlib" "/home/anholt/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-48d342a8b48d1d01.rlib" "/home/anholt/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libminiz_oxide-14bc0820888c8eb3.rlib" "/home/anholt/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libadler-9cbd9e217bff06bc.rlib" "/home/anholt/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libobject-31826136df98934e.rlib" "/home/anholt/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libaddr2line-075976a117c8fd5d.rlib" "/home/anholt/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgimli-2d5cbedfbf17a011.rlib" "/home/anholt/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-0474372ff08c5319.rlib" "/home/anholt/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-d437c34460d2315a.rlib" "/home/anholt/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-fb61ed1b8cc4de79.rlib" "/home/anholt/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-bf76d1b643bfc9f0.rlib" "/home/anholt/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-a1b53aa7fddcf418.rlib" "/home/anholt/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-28585e57fac45c73.rlib" "/home/anholt/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-64801769bc15ab28.rlib" "/home/anholt/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-541997b56bb98660.rlib" "/home/anholt/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-cdea3c81adab3d12.rlib" "-Wl,--end-group" "/home/anholt/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-cd9f15a39fb65cbc.rlib" "-Wl,-Bdynamic" "-ldl" "-lrt" "-lpthread" "-lgcc_s" "-lc" "-lm" "-lrt" "-lpthread" "-lutil" "-ldl" "-lutil"
  = note: /usr/lib/gcc-cross/i686-linux-gnu/10/../../../../i686-linux-gnu/bin/ld: skipping incompatible /usr/lib/gcc-cross/i686-linux-gnu/10/libgcc.a when searching for -lgcc
          /usr/lib/gcc-cross/i686-linux-gnu/10/../../../../i686-linux-gnu/bin/ld: cannot find -lgcc
          collect2: error: ld returned 1 exit status

error: aborting due to previous error