Meson test tree for rustc detection issue.
I'm working on adding rust to the Mesa meson build, but running into
troubles with my cross files.  One is that the debcrossgen doesn't
include a rustc line, but even with my own rustc added, I get:

anholt@miranda:src/temp/rusttest% meson --cross-file cross_file-i386.txt  build-i386
The Meson build system
Version: 0.55.3
Source dir: /home/anholt/src/temp/rusttest
Build dir: /home/anholt/src/temp/rusttest/build-i386
Build type: cross build
Project name: rusttest
Project version: 1.0
C compiler for the build machine: ccache cc (gcc 10.2.0 "cc (Debian 10.2.0-9) 10.2.0")
C linker for the build machine: cc ld.bfd 2.35.1
C compiler for the host machine: /usr/lib/ccache/i686-linux-gnu-gcc (gcc 10.2.0 "i686-linux-gnu-gcc (Debian 10.2.0-9) 10.2.0")
C linker for the host machine: /usr/lib/ccache/i686-linux-gnu-gcc ld.bfd 2.35.1
Build machine cpu family: x86_64
Build machine cpu: x86_64
Host machine cpu family: x86
Host machine cpu: i386
Target machine cpu family: x86
Target machine cpu: i386
Rust compiler for the build machine: rustc (rustc 1.47.0)
Rust linker for the build machine: rustc ld.bfd 2.35.1
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/mesonbuild/mesonmain.py", line 140, in run
    return options.run_func(options)
  File "/usr/lib/python3/dist-packages/mesonbuild/msetup.py", line 245, in run
    app.generate()
  File "/usr/lib/python3/dist-packages/mesonbuild/msetup.py", line 159, in generate
    self._generate(env)
  File "/usr/lib/python3/dist-packages/mesonbuild/msetup.py", line 192, in _generate
    intr.run()
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreter.py", line 4560, in run
    super().run()
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase.py", line 493, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase.py", line 518, in evaluate_codeblock
    raise e
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase.py", line 511, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase.py", line 524, in evaluate_statement
    return self.function_call(cur)
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase.py", line 879, in function_call
    return func(node, func_args, self.kwargs_string_keys(kwargs))
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase.py", line 378, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase.py", line 213, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase.py", line 182, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreter.py", line 3108, in func_add_languages
    success &= self.add_languages(args, required, MachineChoice.HOST)
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreter.py", line 3206, in add_languages
    success = self.add_languages_for(args, required, for_machine)
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreter.py", line 3244, in add_languages_for
    comp.sanity_check(self.environment.get_scratch_dir(), self.environment)
  File "/usr/lib/python3/dist-packages/mesonbuild/compilers/rust.py", line 74, in sanity_check
    cmdlist = self.exe_wrapper + [output_name]
TypeError: unsupported operand type(s) for +: 'EmptyExternalProgram' and 'list'